const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const root=path.join(__dirname,'../dist'),files=['data.js','lesson-animations.js','learning.js','curriculum-content.js','resource-content.js','international-content.js','world-content.js','curriculum.js'];
const c={document:{getElementById:()=>null},window:{addEventListener:()=>{}}};vm.createContext(c);vm.runInContext(files.map(f=>fs.readFileSync(path.join(root,f),'utf8')).join('\n')+';globalThis.d={lessons,lessonGuides,learningOrder,glossary,learningResources,resourceReadingPaths,worldMarkets,learningGroups}',c);const d=c.d;
assert.equal(d.lessons.length,30);assert.equal(new Set(d.lessons.map(l=>l.id)).size,30);assert.equal(d.learningGroups.length,6);assert.equal(d.learningOrder.length,30);assert.equal(new Set(d.learningOrder).size,30);
for(let id=0;id<30;id++)assert.ok(d.lessons.some(l=>l.id===id),'missing stable ID '+id);
// Recompute the independently specified classroom questions, including units/time conversions.
const expected={13:7*45+20,14:40*(600-250),15:Math.min(70,45+12),16:(20*300+40*600)/60,17:(70-50)*1,18:5*2*(450-300),19:60*1000*80,20:20*(-50)+20*350,21:80*380+80*(420-400),22:8000*(.55+.18)+160,23:60**2+25**2+15**2,24:100+40*.5*.9,25:(120-80)*.5*3,26:Math.round((-100000+60000/1.1+60000/1.1**2)*100)/100,27:10*60,28:30*.5*(80-50)};
for(const [id,value] of Object.entries(expected))assert.ok(Math.abs(d.lessonGuides[id].task[1]-value)<1e-8,`numerical answer ${id}`);
for(const l of d.lessons){const g=d.lessonGuides[l.id];assert.ok(g?.goal&&g.example?.length===2);assert.ok(l.sections.length>=4);assert.ok(l.sources.length);assert.ok(l.pitfalls.length);for(const id of g.pre)assert.ok(d.learningOrder.indexOf(id)<d.learningOrder.indexOf(l.id),`prerequisite ordering ${l.id} <- ${id}`);for(const t of g.terms)assert.ok(d.glossary[t],`missing glossary ${t}`);assert.equal(l.quiz.options.length,3);assert.ok(Number.isInteger(l.quiz.answer)&&l.quiz.answer>=0&&l.quiz.answer<3);if(g.task)assert.ok(Number.isFinite(g.task[1])&&g.task[2]&&g.task[3]);for(const s of l.sources)assert.ok(s.title&&s.organization&&/^https:\/\//.test(s.url));}
assert.equal(d.learningResources.length,15);assert.equal(new Set(d.learningResources.map(r=>r.id)).size,15);
for(const r of d.learningResources){assert.ok(/^https:\/\//.test(r.url));assert.ok(r.license&&r.access&&r.language&&r.date);assert.equal(r.path.length,3);for(const id of r.lessonIds)assert.ok(d.lessons.some(l=>l.id===id));}
for(const p of d.resourceReadingPaths)for(const id of p.ids)assert.ok(d.learningResources.some(r=>r.id===id));
assert.equal(d.worldMarkets.length,16);assert.equal(new Set(d.worldMarkets.map(m=>m.id)).size,16);assert.equal(new Set(d.worldMarkets.map(m=>m.country)).size,15);
const fields=['governance','sequence','pricing','balance','adequacy','transition'];for(const m of d.worldMarkets){assert.ok(m.scope&&m.caution&&m.sources.length>=3&&m.checked==='2026-10-07');for(const f of fields){assert.ok(m[f].length>=40);assert.ok(m.fieldSources[f].length);for(const i of m.fieldSources[f])assert.ok(m.sources[i]?.url);}assert.ok(m.case.title&&m.case.formula&&m.case.boundary);for(const s of m.sources)assert.ok(s.title&&s.organization&&/^https:\/\//.test(s.url));}
const index=fs.readFileSync(path.join(root,'index.html'),'utf8');for(const file of files.slice(3))assert.ok(index.includes(`src="${file}"`));assert.ok(index.indexOf('curriculum.js')<index.indexOf('app.js'));assert.ok(index.includes('academy.css'));
console.log('PASS 30 stable lessons, 6 ordered modules, source/glossary coverage, 15 resource guides, 15 countries/16 scoped cases and valid field citations.');
