const assert=require('node:assert/strict');
const fs=require('node:fs');const vm=require('node:vm');
const E=require('../dist/planner-engine.js');
const context=vm.createContext({structuredClone,PlannerEngine:E});
vm.runInContext(fs.readFileSync(require.resolve('../dist/planner-ui.js'),'utf8')+'\nglobalThis.defaults=plannerDefaults;',context);
const p=structuredClone(context.defaults);
const near=(a,b)=>assert.ok(Math.abs(a-b)<1e-5,`${a} != ${b}`);
const fixture={...p,load:Array(24).fill(100),solar:Array(24).fill(0),buy:Array.from({length:24},(_,h)=>h<12?.2:1),sell:Array(24).fill(.1),pvKw:0,storageKw:10,storageKwh:20,dod:100,efficiency:100,reserve:0,days:365,years:1,storageCost:1,storageOm:0,siteCost:0,annualFixed:0,discount:0,replaceYear:0};
const arbitrage=E.evaluate(fixture,'storage');near(arbitrage.first.charge,20);near(arbitrage.first.discharge,20);near(arbitrage.annualEnergy,16*365);near(arbitrage.npv,16*365-20);
const baseline=E.evaluate(p,'baseline');near(baseline.capex,0);near(baseline.npv,0);
const combo=E.evaluate(p,'combo');let soc=0;
for(const h of combo.first.hours){
 near(h.pv+h.importKwh+h.discharge,h.load+h.charge+h.exportKwh+h.curtail);
 assert.ok(!(h.charge>1e-7&&h.discharge>1e-7));
 assert.ok(h.charge<=p.storageKw+1e-7&&h.discharge<=p.storageKw+1e-7);
 const next=soc+h.charge*Math.sqrt(p.efficiency/100)-h.discharge/Math.sqrt(p.efficiency/100);near(next,h.soc);soc=h.soc;
 assert.ok(h.soc>=-1e-7&&h.soc<=p.storageKwh*p.dod/100+1e-7);
 assert.ok(h.exportKwh<=p.exportLimit+1e-7);
}near(soc,0);
near(combo.pvReference+combo.storageIncrement,combo.annualEnergy);
near(combo.rows[0].cash,combo.rows[0].savings+combo.rows[0].exports+combo.rows[0].mechanism+combo.rows[0].extra-combo.rows[0].om-combo.rows[0].replacement);
const loss=E.evaluate({...fixture,efficiency:81},'storage');assert.ok(loss.first.charge>loss.first.discharge);assert.ok(loss.annualEnergy<arbitrage.annualEnergy);
const zero=E.evaluate({...fixture,storageKw:0,storageKwh:0},'storage');near(zero.npv,0);
const negative=E.evaluate({...p,sell:Array(24).fill(-.1),mechanismConfirmed:false},'pv');near(negative.first.exportKwh,0);assert.ok(negative.first.curtail>0);
const withUnconfirmed=E.evaluate({...p,mechanismPct:100,responseAnnual:10000,demandAnnual:10000},'combo');near(withUnconfirmed.rows[0].extra,0);near(withUnconfirmed.rows[0].mechanism,0);
const mech=E.evaluate({...p,mechanismConfirmed:true,mechanismPct:50,mechanismPrice:.5,referencePrice:.3,mechanismYears:1},'pv');near(mech.rows[0].mechanism,mech.first.exportKwh*p.days*.1);near(mech.rows[1].mechanism,0);
const noExport=E.evaluate({...p,exportLimit:0,mechanismConfirmed:true,mechanismPct:100},'combo');near(noExport.rows[0].mechanism,0);near(noExport.first.exportKwh,0);
assert.throws(()=>E.validate({...p,load:[1,2]}));assert.throws(()=>E.validate({...p,load:Array(24).fill(-1)}));assert.throws(()=>E.validate({...p,years:1.5}));assert.throws(()=>E.validate({...p,efficiency:101}));
assert.throws(()=>E.validate({...p,extrasConfirmed:true,responseAnnual:100,reserve:0}));
const replacement=combo.rows.find(x=>x.year===p.replaceYear);near(replacement.replacement,p.storageKwh*p.storageCost*p.replacePct/100);
assert.equal(E.irr([-100,230,-132]),null);near(E.irr([-100,110]),.1);near(E.npv([-100,110],.1),0);
vm.runInContext(fs.readFileSync(require.resolve('../dist/planner-policy.js'),'utf8')+'\nglobalThis.policies=plannerPolicies;',context);assert.deepEqual(Object.keys(context.policies).sort(),['山东','山西','广东','江苏','浙江','蒙西'].sort());
for(const policy of Object.values(context.policies))assert.ok(policy.sources.every(([t,u])=>t&&new URL(u).protocol==='https:'));
console.log('PASS: energy conservation, cyclic SOC, power limits, arbitrage, losses, double-counting, conditional revenue, expiry, replacement, NPV/IRR and six regional policies.');
